name: CI Pipeline

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  pip install flask pytest
            - name: Run tests
              run: pytest
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Deploy with Docker
              run: |
                  docker build -t flask-app-1 ./
                  docker run -d -p 5000:5000 flask-app-1
    notify:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  STATUS: success
